### ISSUE TITLE
Unnecessary console.log

### ISSUE THREAD

**Issue by imjack** [forwardemail/preview-email#14]
Hi,

Whilst using this with email-templates I get the debug logging shown in the link.
https://github.com/forwardemail/preview-email/blob/master/src/index.js#L42

I think these should be removed.

**Comment by niftylettuce** [comment]
nice find, sorry about that, sec

**Comment by niftylettuce** [comment]
preview-email v2.0.1 released to npm

email-templates v7.0.3 released to npm

**Comment by imjack** [comment]
Thanks!
