### ISSUE TITLE
The result of email rendering is within <iframe> tage

### ISSUE THREAD

**Issue by ohkimchi** [forwardemail/preview-email#17]
Hi, I am using this preview-email to test if my template.pug display properly. When it render my template.pug in the message, everything from my template.pug is wrapped inside the <iframe>, and the font in the head was also in the iframe and not reflected in my email content. Can you have a look at it?

**Comment by niftylettuce** [comment]
Can you share a reproducible example?  Perhaps make a test repository on GitHub and send me a link?  Or screenshots and some code snippets?  Would love to help.
