### ISSUE TITLE
Problem with WSL path

### ISSUE THREAD

**Issue by aileo** [forwardemail/preview-email#18]
I am using this package through email-templates in a WSL environment. It opens chrome for the WSL as explained [here](https://github.com/sindresorhus/open#app), but it does not open the html generated file.

I specified a path like `/mnt/c/...` for `dir` option so both windows and WSL can access. It writes the html correctly, but does not load the page in chrome.

I think it is due to chrome on windows that does not understand WSL formatted path, I tested replacing [this](https://github.com/forwardemail/preview-email/blob/master/src/index.js#L55) by:
```js
if (options.open) await open(filePath.replace('/mnt/c', 'C:').replace('/', '\\'), options.open);
```
and it worked as expected (but it is not reliable at all).

I don't know if it is really an issue with this package or if it should be supported... Maybe just adding an option that takes a function to transform path to give to `open` could do the job at a minimal cost.

**Comment by niftylettuce** [comment]
I would gladly accept a PR and possibly tests too if you don't mind.  Thanks @aileo
