### ISSUE TITLE
Option `open` is incorrectly handled and/or documented

### ISSUE THREAD

**Issue by euvs** [forwardemail/preview-email#20]
According to the readme, the`open` option is supposed to be a Boolean or an object of the `{ wait: false }` format. However in the code it only checks for boolean. 

https://github.com/forwardemail/preview-email/blob/4e48c73756b13599bbff92e30fe20a9bf1dd54e5/src/index.js#L55

If `{ wait: false }` is passed it will always be `true`

**Comment by niftylettuce** [comment]
PR welcome!
