### ISSUE TITLE
Mailparser update

### ISSUE THREAD

**Issue by cythrawll** [forwardemail/preview-email#26]
So it looks like a few hours ago nodemailer/mailparser reverted 3.0.1 back to MIT (yay!). And this version has the vulnerability fixed packages as well.

**Comment by niftylettuce** [comment]
done <https://github.com/forwardemail/preview-email/releases/tag/v3.0.3>

and in email-templates too https://github.com/forwardemail/email-templates/releases/tag/v8.0.2
